image: alpine/edge
packages:
  - libgcc
  - rust
  - cargo
sources:
  - https://git.sr.ht/~andrewzah/danmuji
tasks:
  - test: |
      cd danmuji
      cargo fmt --all -- --check
      cargo build
      cargo test
