image: alpine/edge
environment:
  GOPATH: /tmp
  GOBIN: /tmp/bin
  GOPROJPATH: /tmp/src/git.sr.ht/~andrewzah/danmuji
packages:
  - go
sources:
  - https://git.sr.ht/~andrewzah/danmuji/
tasks:
  - setup: |
      # use golang's stupid setup
      mkdir -p $GOBIN
      mkdir -p $GOPROJPATH
      cd danmuji
      mv -v * $GOPROJPATH
  - deps: |
      cd $GOPROJPATH
      go get -u github.com/golang/dep/cmd/dep
      /tmp/bin/dep ensure
  - build: |
      cd $GOPROJPATH
      go build app/*
  - test: |
      cd $GOPROJPATH
      go test -v app/*
triggers:
- action: email
  condition: failure
  to: Andrew Zah <zah@andrewzah.com>
