[package]
name = "danmuji"
version = "0.1.0"
authors = ["Andrew Zah <zah@andrewzah.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
diesel = { version = "1.4", features = ["chrono", "r2d2", "postgres"] }
dotenv = "0.14.1"
env_logger = "0.6"
hey_listen = "0.4"
lazy_static = "1.3"
log = "0.4"
pretty_assertions = "0.6.1"
r2d2 = "0.8.5"
regex = "1"
serenity = "0.6.0"
serde_json = "1.0.40"
white_rabbit = "0.1.1"
