[package]
name = "danmuji"
version = "0.1.0"
authors = ["Andrew Zah <zah@andrewzah.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4", features = ["r2d2", "postgres"] }
dotenv = "0.14.1"
env_logger = "0.6"
lazy_static = "1.3"
log = "0.4"
regex = "1"
serenity = "0.6.0"
