binop_separator = "Front"
comment_width = 95
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_block_trailing_comma = true
merge_imports = true
reorder_imports = true
wrap_comments = true
