ALTER TABLE replies
ADD COLUMN guild_id VARCHAR (20) NOT NULL DEFAULT '490547765596782602',
DROP CONSTRAINT IF EXISTS replies_tag_key;

DROP INDEX IF EXISTS tag;
CREATE UNIQUE INDEX guild_tag ON replies (guild_id, tag);
